# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Encuesta CPI

on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Use Node.js 
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install Angula CLI
      run: npm install -g @angular/cli

    - name:  Go to Angular app folder and build Angular files to statics for production
      run: cd src/main/webapp/inscripcionUNQ-app && npm install && ng build --prod

    - name: Build with Maven
      run: mvn install && ls -l target

    - name: Create dist dirs
      run: mkdir -p dist/static && mkdir -p dist/war

    - name: Copy statics files to dist/statis
      run:  cp -Rf src/main/webapp/inscripcionUNQ-app/dist/inscripcionUNQ-app/* dist/static/
    
    - name: Copy wars to dist/war
      run:  cp -Rf target/*.war dist/war/
      
    - name: List dist files
      run: find dist

    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: matiasmpereira/encuesta-cpi-frontend
        tags: latest
