# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Use Node.js and Angula CLI
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install -g @angular/cli
    - name: Install npm deps
    - run: cd src/main/webapp/inscripcionUNQ-app
    - run: npm install
    - name: Build Angular files to statics for production
    - run: ng build --prod

    - name: Build with Maven
      run: mvn install && ls -l target

    
